services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.10
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    volumes:
      - zookeeper_log:/var/lib/zookeeper/log
      - zookeeper_data:/var/lib/zookeeper/data
    networks:
      - confluent
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
  x-kafka-common:
    &kafka-common
    image: confluentinc/cp-kafka:7.0.10
    depends_on:
      - zookeeper
    environment:
      &kafka-common-env
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: false
      KAFKA_DELETE_TOPIC_ENABLE: false
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      # KAFKA_SSL_KEYSTORE_FILENAME: kafka.kafka-1.keystore.pkcs12
      # KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-1_keystore_creds
      # KAFKA_SSL_KEY_CREDENTIALS: kafka-1_sslkey_creds
      # KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka-1.truststore.jks
      # KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-1_truststore_creds
      # KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
    hostname: kafka
    networks:
      - confluent
  kafka-1:
    <<: *kafka-common
    restart: always
    container_name: kafka-1
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ./kafka-1-creds:/etc/kafka/secrets
      - kafka_1:/var/lib/kafka/data
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  kafka-2:
    <<: *kafka-common
    restart: always
    container_name: kafka-2
    ports:
      - 9094:9092
      - 9095:9093
    volumes:
      - ./kafka-1-creds:/etc/kafka/secrets
      - kafka_2:/var/lib/kafka/data
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
  kafka-3:
    <<: *kafka-common
    restart: always
    container_name: kafka-3
    ports:
      - 9096:9092
      - 9097:9093
    volumes:
      - ./kafka-1-creds:/etc/kafka/secrets
      - kafka_3:/var/lib/kafka/data
    environment:
      <<: *kafka-common-env
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9096
    
  vault:
    image: hashicorp/vault
    container_name: vault-new
    environment:
      VAULT_ADDR: "0.0.0.0:8200"
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    volumes:
      - ./logs:/vault/logs/:rw
      - ./data:/vault/data/:rw
      - ./config:/vault/config/:rw
      - ./certs:/certs/:rw
      - ./file:/vault/file/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl

volumes:
  zookeeper_log:
  zookeeper_data:
  kafka_1:
  kafka_2:
  kafka_3:
  vault:

networks:
  confluent: